### PR TITLE
Validation value can be 0

### PR DESCRIPTION
**Pull request by Ninos**
See also #2047

I removed #2048 by mistake, sry.

PS: this is not due the fields, this code just affects the validation
functions (Easier to test). I've tested some validation functions and
all worked as they should.

### CODE REVIEW

**Comment by kprovance** [comment]
Some?  How about all, so in the event something is broken, *I* don;t have to fix it?  :)

**Comment by Ninos** [comment]
I'll check all validations tomorrow :)

**Comment by Ninos** [comment]
Ok tested all validations and have found no errors. I think this pr can be merged

**Comment by dovy** [comment]
Manually merged. Thanks!

**Pull request closed without merging**
