### PR TITLE
Added: Linked for color field

### PR DESCRIPTION
**Pull request by Ninos**
With this changes you can link a changed color of the defined color field to other fields. So for example if you change the primary_color field to `#000000`, all linked fields will also be changed to `#000000`. It also supports alpha values.

Atm linked fields can just be defined for the color field. The supported linked fields are background, border, color, color_gradient, color_rgba, link_color & typography.

Here's an example of code:

```
array(
    'id'                    => 'color_primary',
    'type'                  => 'color',
    'title'                 => 'Primary Color',
    'default'               => '#ffffff',
    'linked'                => array(
        'color_secondary' => array(
            'color' => true  // color of "color_secondary" will be rewritten with the new color of "color_primary" (default)
        ),
        'background_header' => array(
            'color' => true, // color of "background_header" will be rewritten with the new color of "color_primary" (default)
            'alpha' => '0.5' // alpha of "background_header" will be changed to 0.5 (if exists)
        ),
        'background_footer' => array(
            'color' => true,
            'alpha' => true // alpha of "background_header" will not be changed (default)
        )
    )
)
```

you could also write:

```
array(
    'id'                    => 'color_primary',
    'type'                  => 'color',
    'title'                 => 'Primary Color',
    'default'               => '#ffffff',
    'linked'                => array(
        'color_secondary' => array(),
        'background_header' => array(
            'alpha' => '0.5'
        ),
        'background_footer' => array()
    )
)
```

So true is the default value and means, if available, take the value of the color field you linked from, otherwise use the already existing value of the linked field. If the value is defined, this one will always be used.

### CODE REVIEW

**Comment by Ninos** [comment]
@dovy should be finished now :-)

**Comment by dovy** [comment]
Give me a little bit to look this one over. Don't want to break anything.  ;)

**Comment by Ninos** [comment]
Hey @dovy are there some news about this pr or are you still short of time? :-)

**Comment by dovy** [comment]
Webinar tomorrow. Been a tiny bit out of time.  :P

**Comment by Ninos** [comment]
Ah ok :D

**Comment by Ninos** [comment]
@kprovance why was this PR closed?

**Comment by kprovance** [comment]
We're going a different route for Redux 4

**Comment by Ninos** [comment]
Ok, thx

**Pull request closed without merging**
