### PR TITLE
Fix editor issues for repeater extension

### PR DESCRIPTION
**Pull request by FFIN**
Fix for [redux-extensions Issues 240](https://github.com/reduxframework/redux-extensions/issues/240)
I don't know this is a smart way to do it, but makes editor for repeater extension to work.

### CODE REVIEW

**Comment by dovy** [comment]
I'll try this out. If you solved it, I love you! hah.

**Comment by FFIN** [comment]
Just an update @dovy .
My previous PR apparently incomplete, it just fix css issues.
When you click "add", it inserting a broken editor.

But I finally make it work !
For those editors in repeater extensions to work, it need to add some lines to `field_repeater.js`.
Since it's premium extension, I can't make a PR.

What would you want me to do?
Obviously, you don't want premium extension source code pasting here, right?

**Comment by dovy** [comment]
Correct. Send me an email to dovy@redux.io.

I'd love to get that.  :)

**Comment by FFIN** [comment]
It's on its way @dovy .
Just sent you an email.
That file needs to work with this PR #2889

**Comment by dovy** [comment]
Just in case that doesn't work, try dovy@reduxframework.com too.  ;)

**Comment by dovy** [comment]
And thanks!

**Comment by dovy** [comment]
Hmm, doesn't seem to be coming through. Care to try Slack? http://slack.redux.io

**Comment by FFIN** [comment]
Just sent you via slack !

**Comment by kprovance** [comment]
Was this handled?  Please reply in two days, or I need to close this ticket.  Thanks!

**Comment by FFIN** [comment]
Well, I've sent modifications to @dovy , I guess this ticket's status is all up to him now... :)

**Pull request closed without merging**
