### PR TITLE
Fix for #1756

### PR DESCRIPTION
**Pull request by FFIN**
Fix for #1756 
Changing nested foreach key variables `$k` to `$l`

### CODE REVIEW

**Comment by dovy** [comment]
So you have confirmed this works for you? Solves the issue?

**Comment by FFIN** [comment]
Yes @dovy . It works for me.
I guess this is more like server os and php version issue.
But changing those variables have no harm to others anyway.

**Comment by kprovance** [comment]
@FFIN  - I'm going to use your fix, but instead of `$l`, I'm going to use and actual term (key, or idx), to not only solve this issue, but for readability's sake.  I will credit you in the changelog.  :)

**Comment by FFIN** [comment]
@kprovance - Thanks for the credit !
>  I'm going to use and actual term (key, or idx), to not only solve this issue, but for readability's sake.
Sure thing, for the key, I usually use that, too. :)

**Pull request closed without merging**
