### PR TITLE
WP.org compatible readme

### PR DESCRIPTION
**Pull request by szepeviktor**
See: https://wordpress.org/plugins/redux-framework/changelog/
Please write a WP.org release script: https://github.com/xwp/wp-dev-lib

### CODE REVIEW

**Comment by dovy** [comment]
Oops. Thanks.

But what's the WP.org release script: https://github.com/xwp/wp-dev-lib for?

**Comment by szepeviktor** [comment]
You could automate WP.org release process.
E.g. convert CHANGELOG.md into readme.txt.
wp-dev-lib is a very good foundation.

**Comment by szepeviktor** [comment]
Don't forget to copy this PR to WP.org: trunk and the last tag.

**Comment by dovy** [comment]
I'll be updating to 3.5.0.1 soon. So yes, we'll do that.

**Pull request merged**
