### PR TITLE
Pull from master

### PR DESCRIPTION
**Pull request by chirox**
Pull all changes from master

### CODE REVIEW

**Comment by kprovance** [comment]
So, what exactly is 'sfsection', and why would it be beneficial to our users?  Sell us on it.

**Comment by chirox** [comment]
So sorry that my mistake i just need pull changes from master to my fork

**Comment by dovy** [comment]
Still, what is it?  heh.

**Comment by kprovance** [comment]
Haccident Appen.  Cheers.

**Comment by kprovance** [comment]
Wait.  SF.  Swift?  One of Ed's mates?  :)

**Comment by chirox** [comment]
No, just my prefix for some custom on that field :)

**Comment by kprovance** [comment]
Ah, cool.  Just FYI, adding stuff to the core in a 'custom; build of Redux can be unpredictable.  Why?  Well, if you are embedding and someone else using Redux goes for the plugin option, the plugin will override your embed.  That is by design.  If you are using a customized plugin version, updates will wipe out your additions.  What we have to avoid those situations are field overloading or the extension boilerplate (I recommend the latter).  With extensions you can make as many fields as you like and activate them with one line of code (https://docs.reduxframework.com/core/redux-api/) and never have to worry about updated messing up your customizing.

https://docs.reduxframework.com/extensions/using-extensions/

Just from friendly advice to save you some pain.  Best of luck.

**Comment by chirox** [comment]
Wow, thanks for your advice, that help me a lot.

**Pull request closed without merging**
