### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by nigrosimone**
- Fix some strange code (continue after return and method without final return)
- little performance improvements on: cast array VS is_array (cast array is more fast)

from profiler:

```
                                  Inv.Count     Self Cost    Total Cost
OLD recursive_array_search()      5769          7.94         22.97
NEW recursive_array_search()      5769          1.56         3.38
```

### CODE REVIEW

**Comment by mabbas64** [comment]
Great job on this one @nigrosimone !

**Comment by nigrosimone** [comment]
news?

**Comment by Basilakis** [comment]
Please accept it.

**Comment by kprovance** [comment]
Did we actually check this live, or is this something that will blow up and Ill have to fix later.  I thought we betted these things more carefully instead of bowing to pressure.  Do I need to list every 'fix' that backfired because it didn't get checked?

**Comment by nigrosimone** [comment]
Pull request is 5 months ago. It is a lot of time for test.

**Comment by kprovance** [comment]
It's a time/cost thing.  You get we make NOTHING off of Redux itself, right?  That we have REAL jobs too.  Plus, all the pushiness came over the holiday break.  Not sure why that was a thing.

**Comment by kprovance** [comment]
Congrats guys, the compltey broke how the option panel renders!  I have to undo it.  Next time, lets freakin CHECK THESE THINGS FIRST!!!!!

**Comment by dovy** [comment]
@kprovance Give more details on that. Seemed to work for me. What is the specific case of failure? Fields, etc...

**Comment by kprovance** [comment]
Load it up with my theme and watch panels render right down the bottom of the page.  I think it has something to do with the repeater, that's where is went to hell.  I'm not trying to be an egomanic here, but my code worked for years.  Why are we fixing something that isn't broke?

**Comment by nigrosimone** [comment]
@kprovance it works for me. 

> I think it has something to do with the repeate

What line of code of my pr do you think has broken redux?

**Comment by kprovance** [comment]
I'm glad it works for you, but it totally messed up my panel, so I reversed it.  Needs of the many and all that.  If Dovy wants to take the time to delve into the repeater code, then he's free to to that.  My code works, that's all I care about.  I don't have the time or inclination to figure why this so called 'fix' broke what wasn't broken.

**Comment by nigrosimone** [comment]
Ok, but why do you  think this pr has introduced the error?

**Comment by kprovance** [comment]
Because I undid it and my panel was fixed?

**Comment by kprovance** [comment]
I don't have the time to figure out why this code is bad.  It is, at least inasfar as the repeater field goes.  Again, if Dovy wants to look into at, as repeater field is his, then great.  Personally, I do not.  I have to make money for a living instead of wasting another half a day figuring out why my panel was all messed up.

**Comment by nigrosimone** [comment]
@kprovance take it easy... 

@dovy i think the only possible problem is on line 51 of my edits https://github.com/reduxframework/redux-framework/pull/3083/files.

**Comment by kprovance** [comment]
Dude, don't tell me me to take it easy, this is FAR from the first time I have had to undo user contributions because it broke something.  I've asked Dovy to properly vet changes numerous times, and he doesn't, which means it's up to me to fix this crap, every time...and I'm getting tired of doing it. Granted, you don't have access to premium extensions, but Dovy does, and it should have been vetted, which makes it my problem and I have to spend a half a day figuring out why the option panel in my theme is broken.  There is a process here, and it's not being follwoed.  Iam sorry you are stuck in the middle, but until these proposed changes work with everything, I can't let it pass?  What would have happened if these changes were pushed to wp.org and all of a sudden every repeater user begins to complain about a broken panel?  You know who has to deal with that?  Me?  I am I make no money off the repeater field.  I'm heading off a major headache right now.  But again, if Dovy wants to take the time to figure out why the repeater field blows up the panel with this change, it's up to him.  He has a full time job and a family to see after, so, it might take longer than a few months.  Point is, my code works, it's not broken, I don't see a need to fix it right now.

**Pull request merged**
