### PR TITLE
Coding standards

### PR DESCRIPTION
**Pull request by aristath**
This is an effort to make the Redux Framework use WordPress Coding standards and best practices.
I already wrote an autoloader for it and I'll be gradually renaming files & classes to follow WP Coding standards.

This is not to be merged yet, there's lots of work to be done here.

### CODE REVIEW

**Comment by kprovance** [comment]
I think we three need to chat about this.  I hate, hate, HATE 'endif'.  I've gone to a great deal of trouble over the years to clean up all that - IMHO, bad practice.  And the HUGE indentations?  No.  Sorry.  Unreadable for me.

**Comment by aristath** [comment]
I converted some identations to tabs instead of spaces 'cause that's what the WP Coding standards dictate. I then talked to @dovy and he mentioned you guys prefer spaces so I'll convert these back to spaces, no harm done.
As for the endifs, these will go.
As soon as I migrate classes to use the autoloader instead of being loaded the way they are now, the conditional wrappers for classes will no longer be necessary.

**Comment by kprovance** [comment]
Um.  Again, maybe we should discuss this first.  "Look at our code" and change things around are two different things.  I need to understand why why and the benefit, with the additional responsibility of making sure things don't get broken, because it's usually I who ended up having to fix things...and I don't like fixing what isn't broken.  So, maybe Monday the three of us can evaluate these things before making them permanent.

**Comment by aristath** [comment]
That's why in my initial post for this PR I mentioned 
> This is not to be merged

**Comment by justnorris** [comment]
Loving these changes @aristath .
In my opinion - if you're developing a plugin for Wordpress Developers, you should probably comply with at least most of the coding standards. 

As for the Tabs vs. Spaces - of course tabs. You like small indentation space, I prefer large space. Tabs allow that, spaces don't.

**Comment by kprovance** [comment]
Redux is also an embed solution, so not all plugin standards will apply.  And as long as I'm on this project, there will never, ever be tabs.  It's ugly and difficult to read.  Since Dovy and I are the ones who work on the code the most, chances are we'll keep the standard we are happy with.

**Comment by aristath** [comment]
Did you look at the code?
Tabs have already been removed and converted to spaces.
Unless I missed a file somewhere.

**Comment by aristath** [comment]
And I didn't follow "plugin standards" anywhere.
These are global [WordPress Coding Standards](https://make.wordpress.org/core/handbook/coding-standards/php/), no matter if we're on a plugin or theme.
I'm trying to follow EVERYTHING except the indentation since you guys prefer spaces.

Indentation however is just a small portion of the coding standards, there are lots of other things too.
Right now most classes follow JS coding standards, not PHP or WordPress.
I'm trying to fix that and use proper filenames & classnames for PHP classes.

The fact that "it works" doesn't mean that it can't be improved.

**Comment by kprovance** [comment]
Again, this is why we need to chat about this.  Some of the changes you are proposing - I think - will break compatibility.  Not all people use Redux as a plugin.  Does putting an 'autoloader' in the plugin file still work on embed solutions?  They've not been tested against our extension library, and metaboxes, and repeater.  There are many, many other considerations here.  I'm also NOT a fan of removing class_exist checks.  This isn't Kirki, this is Redux.  ;-)

**Comment by kprovance** [comment]
<blockquote>
The fact that "it works" doesn't mean that it can't be improved.
</blockquote>
That's not someplace you want to go, dude.  Seriously.  Let it go for now.

**Comment by aristath** [comment]
Yes, it will work on embed solutions.
I define a `REDUX_PATH` on lines 34-36, and I check if the class exists on lines 44-46 inside the autoloader:
https://github.com/aristath/redux-framework/blob/5832451b5da196e6db32ab5d98b348b81e553676/redux-framework.php#L34-L65

**Comment by kprovance** [comment]
Not a fan of DEFINE either.  User defined global variables are a mess.  This is why we have classes and pointers.

**Comment by aristath** [comment]
You can't reject the whole because you don't like a particular line.
The fact that you're not a fan of a single line doesn't mean that the whole is bad, it means that we can just improve that part of it.

This PR is just a suggestion of things that I **personally** think are wrong with the plugin, things that I would like to see improved.
That's the whole point of open-source. Everyone can make suggestions, and then we can talk about them and see what's best for the whole project.
I'm not saying that what I do is right and what you're doing is wrong, what I'm saying is that WordPress has some guidelines and it would be best if we follow those guidelines.

> This isn't Kirki, this is Redux.
The fact that Redux has a larger user-base than Kirki doesn't make this comment valid, nor does it even give you the right to make such a comment. It just means that it's been around longer. Instead of looking down on others perhaps you could just take a look at what they are suggesting. Who knows, it might not be that bad.

> That's not someplace you want to go, dude. Seriously. Let it go for now.
I mentioned that the fact that "it works" doesn't mean that it can't be improved. That's not an opinion, that's a fact. No code is perfect, everything can be improved.

I'm sure there are errors in my code too, no doubt about that.

The changes that were made thus far are:

* Removing unnecessary spacing:
Is there any reason to write something like this:
```php
<?php
    code starts here
```
instead of this?
```php
<?php
code starts here
```

* Renamed some classes and their filenames according to WordPress coding standards: https://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions
I then removed the `if ( class_exists( 'classname' ) ) { }` around classes and wrote an autoloader for these classes so they are loaded when needed, without the need to manually include these files. The check for whether the class exists or not is now in the autoloader. No need to write something on each file when we can have it in just 1 place and it's applied everywhere. DRY is not a bad thing.

I don't see anything wrong with these changes, if you do then I'd be more than happy to hear your opinion and improve that code so that the whole project benefits.

This is an open-source project used by thousands of people, I'm sure that "not a fan" is not a satisfactory answer to a suggestion.

What will the suggested changes changes achieve? Well, for starters we'll be able to make the code more readable and in the future we'll be able to more efficiently organise the code. At some point we'll have to split some monster-classes into smaller parts and make this even more modular.
This PR is a starting point for discussion and what we can improve. Nothing more than that.

**Comment by justnorris** [comment]
@kprovance 
> Since Dovy and I are the ones who work on the code the most, chances are we'll keep the standard we are happy with.
And with that attitude, you'll keep it that way. If that's the intention, that's great. I'm never going to write code with 2-spaced indentation unless I really, really have to. 

I just hope you let @aristath clean up the code. 

> This is an open-source project used by thousands of people, I'm sure that "not a fan" is not a satisfactory answer to a suggestion.

+1

**Comment by aristath** [comment]
@kprovance Right now I made it use 4-space indention.
Do you want me to switch to 2 spaces?

**Comment by kprovance** [comment]
I wouldn't get your hopes up.  That guy's been on this project for like...a minute?  It doesn't matter really, I can still go back in and undo all that damage.

**Comment by aristath** [comment]
@kprovance I don't know how you do things, but I would never merge a PR without talking it over with the rest of you.

> I can still go back in and undo all that damage.

Are you seriously that arrogant to assume that whatever anyone else does is "damage"?
Seriously man???

**Comment by kprovance** [comment]
As much as I would like to answer that, I've been ordered not to.  So, keep pushing.

**Comment by dovy** [comment]
Boys, boys. haha.

@kprovance We'll make sure it's backwards compatible!

@aristath We'll chat about details and preferences.



What I want, as the lead dev.  ;)


ReduxCore is where we're going to stick the loaded. framework.php just becomes a class loaded and we do all the goodness there.

Above that for the plugin, we leave it pretty much the same. As that's just a front-loader for the core.

We prefer spaces and it's been that way, but if the community as a WHOLE (not a few devs) want it tabs, I will listen to the community. We can always change our code formatters to display it the same as spaces.  ;)

In the end we need Redux to be cleaner, more modular, and using the wonderful concepts of autoloaders (php5.3+) so one day, just maybe when WordPress updates its minimum requirements we can move forward.

:)

**Comment by kprovance** [comment]
Now i CAN close this!  Thanks.  Cheers.

**Comment by aristath** [comment]
This is not a race... We're all trying to improve the overall quality of tools that everyone uses.
Whether we work together or not does not change the validity of this pull request.

I hope someday you'll understand that on your own and realise that this is not a race.
There's no antagonising in open-source and nobody is after your job.

That being said, at some point you'll have to improve the overall coding quality and adhere to WordPress coding standards. The sooner it's done the better for Redux.

Cheers and take care.

**Comment by kprovance** [comment]
<blockquote>
That being said, at some point you'll have to improve the overall coding quality and adhere to WordPress coding standards. The sooner it's done the better for Redux.
</blockquote>

Sorry, dude, but I don't drink the automattic kool-aid.  if you enjoy it, then awesome for you, but tabs, like most things outside of America, suck.  Wordpress is not always right, or the defacto, be-all-end-all standard of everything PHP.  Think for yourself, bud.

**Comment by dovy** [comment]
Woah woah... Let's chill out.

We can all be friends. Whew.

**Pull request closed without merging**
