### PR TITLE
Updated .form-table style to only affect redux container and metaboxes

### PR DESCRIPTION
**Pull request by Enchiridion**
I updated the style to only affect redux's content because it was affecting the layout of other plugins metaboxes'.

### CODE REVIEW

**Comment by dovy** [comment]
And this fully works with Redux metaboxes?

**Comment by Enchiridion** [comment]
Yes, that's originally why I made the change, the css was affecting non-redux metabox content.

**Comment by dovy** [comment]
Great. Just wanted to confirm.

**Comment by kprovance** [comment]
Shouldn't metabox specific code have gone in the metabox CSS?  I thought we were keeping extension specific CSS out of the core, or was I wrongly informed?

**Comment by dovy** [comment]
No, we have the .redux0container for everything and that was a global declaration that modified all tables by WordPress. This was a wise change.

**Comment by dovy** [comment]
My bad, @kprovance you're right! We need to move that code for metaboxes in metaboxes.  ;)

**Pull request merged**
