### PR TITLE
 admin footer text 

### PR DESCRIPTION
**Pull request by golchha21**
With this update the admin footer text would be updated to the set value on every page rather than only on the options page.

### CODE REVIEW

**Comment by kprovance** [comment]
You've moved one line of code without changing it.  The point is...what, exactly?

**Comment by golchha21** [comment]
Currently the admin footer text is being called when the options page is been rendered hence the footer text is changed in the options page only and with this change the admin footer text will be called at the time of initialization and hence the footer text will be changed on every admin pages.

**Comment by kprovance** [comment]
We don't want our footer on every admin page.  We're not WooCommerce.

**Comment by golchha21** [comment]
This plugin, repository being public, many developers would like to have this applied, hence suggested this change.
Yes I agree that we are not WooCommerce but still I would insist you to accept this pull request.
Another thing can be done is adding another option[default setting] that would help other developers to override the settings and apply the changes in the footer text as per their choice(only on the options page or to the entire admin section).
The required changes have been made and updated.

**Comment by kprovance** [comment]
If developers want to place a message on every admin page, they may write their own code to do so.  Modifying Redux to do it for them is not the answer.

**Comment by golchha21** [comment]
Done and agreed.

**Pull request closed without merging**
