### PR TITLE
Fixed: Typography field

### PR DESCRIPTION
**Pull request by kisonic**
Fixed: Typography field, Line Height value outputting Font Size value when Line Height left blank.

### CODE REVIEW

**Comment by kprovance** [comment]
That was originally by design.  If we remove this, we break backward compatibility for hundreds of thousands of users, and we won't do that.  The compromise would be to make it an option, which I can put on my to-do list.  :)

**Comment by kisonic** [comment]
You can put this fix on to-do list for next major version.

**Comment by anthonyryanrusso** [comment]
Has this been made an option yet?

**Comment by kprovance** [comment]
No.  Perhaps for the pro version in the workd.

**Comment by anthonyryanrusso** [comment]
Do you all have an ETA on the pro version?

**Comment by kprovance** [comment]
None.  Sorry.

**Pull request closed without merging**
